---
name: datazen
version: "{{major}}.{{minor}}.{{patch}}"
description: "Compile and render schema-validated configuration data."
entry: {{entry}}
requirements:
  - cerberus
  - GitPython
  - Jinja2
  - vcorelib>=0.11.1
dev_requirements:
  - setuptools-wrapper
init_local: |

  DEFAULT_TYPE = "yaml"
  DEFAULT_MANIFEST = f"manifest.{DEFAULT_TYPE}"
  DEFAULT_DIR = f"{PKG_NAME}-out"
  DEFAULT_INDENT = 2
  CACHE_SUFFIX = "_cache"
  GLOBAL_KEY = "global"


  def to_private(input_str: str) -> str:
      """Convert some input to a 'private' String."""

      return f"__{input_str}__"


  ROOT_NAMESPACE = to_private("root")
