name: datazen
version: {{major}}.{{minor}}.{{patch}}
description: "Compile and render schema-validated configuration data."
setup_args:
- entry_override="dz"
init_local: |

  DEFAULT_TYPE = "yaml"
  DEFAULT_MANIFEST = f"manifest.{DEFAULT_TYPE}"
  DEFAULT_DIR = f"{PKG_NAME}-out"
  CACHE_SUFFIX = "_cache"
  GLOBAL_KEY = "global"
  ROOT_NAMESPACE = "__root__"
