---
name: datazen
version: "{{major}}.{{minor}}.{{patch}}"
description: "Compile and render schema-validated configuration data."
entry: {{entry}}
requirements:
  - cerberus
  - GitPython
  - Jinja2
  - vcorelib>=1.0.2
dev_requirements:
  - setuptools-wrapper

init_local: |
  DEFAULT_TYPE = "yaml"
  DEFAULT_MANIFEST = f"manifest.{DEFAULT_TYPE}"
  DEFAULT_DIR = f"{PKG_NAME}-out"
  DEFAULT_INDENT = 2
  CACHE_SUFFIX = "_cache"
  GLOBAL_KEY = "global"


  def to_private(input_str: str) -> str:
      """Convert some input to a 'private' String."""

      return f"__{input_str}__"


  ROOT_NAMESPACE = to_private("root")

mypy_local: |
  [mypy-ruamel.*]
  ignore_missing_imports = True

  [mypy-git.*]
  ignore_missing_imports = True

  [mypy-cerberus.*]
  ignore_missing_imports = True
